name: Daily and PR Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  DependenciesAnalysis:
    permissions:
      security-events: write
    name: DependenciesAnalysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v2.0.2
        with:
          scan-args: |
            --lockfile=app/gradle.lockfile
            --format=sarif
            --output=osv-results.sarif
        continue-on-error: true

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif

  SourceCodeAnalysis:
    permissions:
      security-events: write
    name: SourceCodeAnalysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep for Java
        run: semgrep --config=p/java --sarif --output=semgrep.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif